In [4]:
import numpy as np
a=np.array([[1,2,3,4],[2,1,5,7]])
print(a)


[[1 2 3 4]
 [2 1 5 7]]


In [184]:
b=np.array([2,3,4])
print(b)

[2 3 4]


In [185]:
b=np.array([[9,2,3,3],[3,4,5,6]])
print(b)

[[9 2 3 3]
 [3 4 5 6]]


In [186]:

b.shape

(2, 4)

In [187]:
a.shape


(4,)

In [188]:
a.itemsize

4

In [189]:
a.dtype

dtype('int32')

In [190]:
a.size

4

In [191]:
a=np.array([[1,2,3,4],[1,2,3,4]])
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [192]:
a[1,2]


3

In [193]:
a[0,1]

2

In [194]:
a[:,2]

array([3, 3])

In [195]:
a[1,1:-1:-2]

array([], dtype=int32)

In [5]:
a[1,3]=20
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4]
 [ 2  1  2 20]]


In [9]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
c=b[0,1,1]
print(c)

4


In [19]:
b[:,1,1]=[[[9],[8]]]
print(b)

ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [23]:
np.full_like(a,4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [25]:
np.random.rand(4,2)

array([[0.47165807, 0.21542806],
       [0.37802487, 0.66564814],
       [0.02353936, 0.31876487],
       [0.55885155, 0.48737827]])

In [27]:
np.random.randint(-4,8,size=(3,3))


array([[-1, -2,  0],
       [ 0, -3,  3],
       [ 6, -4,  0]])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a=np.array([[1,2,3]])
r1=np.repeat(a,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
n=np.ones((5,5))
print(n)

z=np.zeros((3,3))
z[1,1]=9
print(z)

n[1:-1,1:-1]=z
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)


[1 2 3]
[100   2   3]


In [38]:
a=np.array([1,3,4])

print(a)
a+2


[1 3 4]


array([3, 5, 6])

In [39]:
a-2

array([-1,  1,  2])

In [40]:
a*2


array([2, 6, 8])

In [41]:
a/2

array([0.5, 1.5, 2. ])

In [42]:
a**2


array([ 1,  9, 16])

In [43]:
np.cos(a)

array([ 0.54030231, -0.9899925 , -0.65364362])

In [44]:
a=np.ones((2,3))
b=np.full((3,2),2)
print(b)
np.matmul(a,b)

[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [45]:
c=np.identity(3)
np.linalg.det(c)


1.0

In [46]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

1

In [48]:
np.max(stats)

6

In [50]:
np.min(stats,axis=1)

array([1, 4])

In [51]:
np.sum(stats,axis=1)

array([ 6, 15])

In [57]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [60]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack([v1,v2,v1,v2]))
np.hstack(([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])