In [183]:
import numpy as np
a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [184]:
b=np.array([2,3,4])
print(b)

[2 3 4]


In [185]:
b=np.array([[9,2,3,3],[3,4,5,6]])
print(b)

[[9 2 3 3]
 [3 4 5 6]]


In [186]:

b.shape

(2, 4)

In [187]:
a.shape


(4,)

In [188]:
a.itemsize

4

In [189]:
a.dtype

dtype('int32')

In [190]:
a.size

4

In [191]:
a=np.array([[1,2,3,4],[1,2,3,4]])
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [192]:
a[1,2]


3

In [193]:
a[0,1]

2

In [194]:
a[:,2]

array([3, 3])

In [195]:
a[1,1:-1:-2]

array([], dtype=int32)